规划设置:
  每日回体           : 240
  每日基建龙门币      : 45000
  每日基建中级作战录像 : 20
  禁用规划路径        : 高级凭证 # 包含这些关键字的获得材料的方式将被禁用，高级凭证用来换角色更好，所以默认禁用

  输出文件           : reports/planning_$TIMESTAMP.txt # $TIMESTAMP 将被替换为时间戳
  显示提升目标消耗    : 否 # 是否显示每一个提升目标所消耗的材料
  显示路径材料变化    : 是 # 是否显示每一个重复操作的路径中获得和消耗的材料总量

提升目标:
-
  干员: 初雪 # 干员姓名
  当前状态:
    等级: 1级
    技能: 7 # 只有一个数字，代表两个技能都是 7 级
  目标状态:
    等级: 精二 1级
    技能: 7, 10 # 多个数字，代表第一个技能 7 级，第二个 10 级
- # 你需要一个短横线在每一个干员数据之前
  干员: 推进之王
  当前状态:
    等级: 精一 50级
    技能: 5
  目标状态:
    等级: 精二 1级
    技能: 10, 10, 10

# 除了为了升级干员所需要的材料，你可以定义额外的目标材料
# 如果该种材料在干员升级时也被使用了，总需求量将相加
目标道具:
#   合成玉: 1w

持有道具:
  龙门币: 14.5w  # 可以使用的后缀：k - 千, w - 万, m - 百万

  资质凭证: 0
  采购凭证: 0

  高级作战记录: 0
  中级作战记录: 0
  初级作战记录: 0
  基础作战记录: 0

  源岩: 0 # 便宜的素材如源岩几乎不影响最终结果
  固源岩: 0
  固源岩组: 0
  提纯源岩: 0 # 昂贵的素材如提纯源岩会较大影响结果

  酯原料: 0
  聚酸酯: 0
  聚酸酯组: 0
  聚酸酯块: 0

  代糖: 0
  糖: 0
  糖组: 0
  糖聚块: 0

  异铁碎片: 0
  异铁: 0
  异铁组: 0
  异铁块: 0

  双酮: 0
  酮凝集: 0
  酮凝集组: 0
  酮阵列: 0

  破损装置: 0
  装置: 0
  全新装置: 0
  改量装置: 0

  RMA70-12: 0
  RMA70-24: 0
  研磨石: 0
  五水研磨石: 0
  轻锰矿: 0
  三水锰矿: 0
  扭转醇: 0
  白马醇: 0

  D32钢: 0
  双极纳米片: 0
  聚合剂: 0

  芯片助剂: 0
  先锋芯片组: 0
  近卫芯片组: 0
  特种芯片组: 0
  辅助芯片组: 0
  辅助双芯片: 0

  技巧概要·卷1: 0
  技巧概要·卷2: 0
  技巧概要·卷3: 0

  骑士金币: 0 # 如果你已经搬空了活动商店，可以考虑在 规划设置 - 禁用规划路径 里添加 活动商店，那么这一个道具就不会被使用
